version: '3'

services:
  frontend:
    build: frontend
    ports:
      - 6970:6970
    depends_on:
      - backend
    volumes:
        - ./storage:/storage
  backend:
    build: backend
    ports:
      - 6969:6969
    volumes:
      - ./storage:/storage
